name: yetoexplore
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  country_code_picker: ^3.3.0
  lottie: ^2.3.1
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.1.0
  http: ^0.13.6
  shared_preferences: ^2.2.0
  hugeicons_pro: ^0.0.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_dark.png
  fonts:
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/poppins_light.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/poppins_medium.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/poppins_semibold.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
